spring.application.name=SpringCore
spring.datasource.url=jdbc:mysql://localhost:3306/data_analysis?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=user
spring.datasource.password=251202

# Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# Logging level
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG